<a href="https://colab.research.google.com/github/sunamkundal01/machine-learning-tutorials/blob/main/bag_of_words_and_feature_term_frequency.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Bag of Words**


A bag of words is a repersentaion of text taht describes the occurances of words with in a document, It involves two things :
1.vocablary of words
2. measure of the presence of known words.


In [30]:
text_data=["The cat sat on the mat",
    "The dog sat on the log",
    "The cat chased the dog",]

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer(stop_words='english')

In [32]:
#fit the data
bow.fit(text_data)

CountVectorizer(stop_words='english')

In [33]:
#get the volcabulary List
bow.get_feature_names_out()

array(['cat', 'chased', 'dog', 'log', 'mat', 'sat'], dtype=object)

In [34]:
# tranform the data
bow_features=bow.transform(text_data)

In [35]:
bow_features

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [36]:
bow_features_array=bow_features.toarray()
bow_features_array

array([[1, 0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 1],
       [1, 1, 1, 0, 0, 0]])

In [37]:
print(bow.get_feature_names_out())
for sentense ,feature in zip(text_data,bow_features_array):
  print(sentense)
  print(feature)

['cat' 'chased' 'dog' 'log' 'mat' 'sat']
The cat sat on the mat
[1 0 0 0 1 1]
The dog sat on the log
[0 0 1 1 0 1]
The cat chased the dog
[1 1 1 0 0 0]


# TF-IF(Term Freqency/ Inverse Documnet Frequency)
TF-IDF it is maeseure ,used in the field of information retrival and machine learning, that can quantify the importance or relevance of string repersentations(eords,phrases,lemmas,etc) in a documnet amongest a colection of documents.

In [38]:
text_data=["The cat sat on the mat",
    "The dog sat on the log",
    "The cat chased the dog",]

In [39]:
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(stop_words='english')

In [40]:
# fit the data
tfidf.fit(text_data)

TfidfVectorizer(stop_words='english')

In [46]:
#get the vocalabary list count how much times word occur
tfidf.vocabulary_

{'cat': 0, 'sat': 5, 'mat': 4, 'dog': 2, 'log': 3, 'chased': 1}

In [47]:
tfidf_features=tfidf.transform(text_data)
tfidf_features

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [48]:
tfidf_features_array=tfidf_features.toarray()
tfidf_features_array


array([[0.51785612, 0.        , 0.        , 0.        , 0.68091856,
        0.51785612],
       [0.        , 0.        , 0.51785612, 0.68091856, 0.        ,
        0.51785612],
       [0.51785612, 0.68091856, 0.51785612, 0.        , 0.        ,
        0.        ]])

In [50]:
for sentense ,feature in zip(text_data,tfidf_features):
  print(sentense)
  print(feature)

The cat sat on the mat
  (0, 0)	0.5178561161676974
  (0, 4)	0.680918560398684
  (0, 5)	0.5178561161676974
The dog sat on the log
  (0, 2)	0.5178561161676974
  (0, 3)	0.680918560398684
  (0, 5)	0.5178561161676974
The cat chased the dog
  (0, 0)	0.5178561161676974
  (0, 1)	0.680918560398684
  (0, 2)	0.5178561161676974
