<a href="https://colab.research.google.com/github/sunamkundal01/pytorch-tutorials/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
!pip list


Package                            Version
---------------------------------- --------------------
absl-py                            1.4.0
accelerate                         0.34.2
aiohappyeyeballs                   2.4.3
aiohttp                            3.10.10
aiosignal                          1.3.1
alabaster                          0.7.16
albucore                           0.0.16
albumentations                     1.4.15
altair                             4.2.2
annotated-types                    0.7.0
anyio                              3.7.1
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.5.1
arviz                              0.19.0
astropy                            6.1.4
astropy-iers-data                  0.2024.10.21.0.33.21
astunparse                         1.6.3
async-timeout                      4.0.3
atpublic                           4.1.0
attrs                              24.2.0
audioread      

In [3]:
import torch
import numpy as np



In [4]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
np1=np.random.rand(3,4)
np1

array([[0.16595972, 0.84410035, 0.93567042, 0.06429703],
       [0.20097899, 0.35005837, 0.62019792, 0.93445074],
       [0.01039201, 0.28956805, 0.41843044, 0.92187824]])

In [6]:
## tensors
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[ 0.9427,  1.7585, -1.1263,  0.9606],
        [ 1.2338, -0.7092, -0.9815, -0.7674],
        [ 0.0517,  0.2043,  0.0881,  1.3661]])

In [8]:
tensor_3d=torch.ones(2,3,4)
tensor_3d

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
## create tensor out of numpy array
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.1660, 0.8441, 0.9357, 0.0643],
        [0.2010, 0.3501, 0.6202, 0.9345],
        [0.0104, 0.2896, 0.4184, 0.9219]], dtype=torch.float64)

In [10]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#reshape and view
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
#reshape if we donr know the number of items using -1
my_torch2=torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch2=my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
my_torch3=torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_torch4=my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
#with reshape and view they will update
my_torch5=torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
my_torch6=my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
my_torch5[1]=4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [20]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
## slicing already know


In [23]:
tensor_a= torch.tensor([1,2,3,4])
tensor_b= torch.tensor([5,6,7,8])

In [24]:
#addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [25]:
# add loghand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# simlarly all airthmetic opertaions


In [26]:
## create  a basic newral network


import torch.nn as nn
import torch.nn.functional as F

In [33]:
# create  a model class that inherits nn.Module
class Model(nn.Module):
  # input layer (4 features of flower)
  # hidden layer1 (no. of neurons)
  # hidden layer2 (no. of neurons)
  # output layer (3 classes)
  def __init__(self,in_features=4,h1=8,h2=9,out_features=3):
    super().__init__() # instantiate our nn.Module
    self.fc1=nn.Linear(in_features,h1)
    self.fc2=nn.Linear(h1,h2)
    self.out=nn.Linear(h2,out_features)

    def forward(self,x):
      x=F.relu(self.fc1(x))
      x=F.relu(self.fc2(x))
      x=self.out(x)
      return x

In [34]:
#pick a manual seed fro randomisation
torch.manual_seed(41)
# create an instances of model
model=Model()